// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  associated_brand: dynamic(() => import("./AssociatedBrand")),
  benifits: dynamic(() => import("./Benifits")),
  download_app: dynamic(() => import("./DownloadApp")),
  feature: dynamic(() => import("./Feature")),
  hero: dynamic(() => import("./Hero")),
  navigation_item: dynamic(() => import("./NavigationItem")),
};
