import type { Metadata } from "next";
import { Inter, } from "next/font/google";
import { PrismicPreview } from "@prismicio/next";
import { createClient, repositoryName } from "@/prismicio";
import Header from "@/components/Header/Header";
import { popins } from "@/utils/fonts";

// CSS
import "@/styles/globals.css";
import Footer from "@/components/Footer/Footer";

export const metadata: Metadata = {
  title: "Smile + Co.",
  description: "Generated by create next app",
  icons: ["favicon.ico"]
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const client = createClient();
  const layout = await client.getSingle('layout')

  return (
    <html lang="en">
      <body className={popins.className}>
      <div className="flex flex-col h-dvh">
          <Header layout={layout}/>
          <section className="flex-grow">
            {children}
          </section>
          <Footer layout={layout}/>
        </div>
        <PrismicPreview repositoryName={repositoryName} />
      </body>
    </html>
  );
}
